name: CI/CD for Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'app/index.html'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'app'  
      - name: Deployment completed
        run: echo "Deployment to S3 completed successfully!"  
          echo "http://${{ secrets.AWS_S3_BUCKET }}.s3.amazonaws.com/index.html"
