# .github/workflows/deploy.yml
name: Deploy to EKS

on:
  push:
    branches:
      - dev
      - master  # Nhánh sản xuất
    paths:
      - 'service/**'  # Chỉ theo dõi sự thay đổi trong thư mục service

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./service  # Build image từ thư mục service
        file: service/Dockerfile
        push: true
        tags: bepython/hello-world:latest
        no-cache: true
  # deploy-dev:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main' # Chỉ chạy khi có thay đổi trên nhánh main và trong thư mục service

  #   steps:
  #   - name: Configure kubectl
  #     uses: azure/setup-kubectl@v1
  #     with:
  #       version: 'latest'

  #   - name: Set up kubeconfig
  #     run: |
  #       aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name <your-cluster-name>

  #   - name: Deploy to EKS (dev)
  #     run: |
  #       kubectl apply -f service/deployment.yaml -n dev # Triển khai vào namespace dev
  #       kubectl apply -f service/service.yaml -n dev
  #       kubectl apply -f service/ingress.yaml -n dev

  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/master' 
  #   steps:
  #   - name: Configure kubectl
  #     uses: azure/setup-kubectl@v1
  #     with:
  #       version: 'latest'

  #   - name: Set up kubeconfig
  #     run: |
  #       aws eks update-kubeconfig --region <your-region> --name <your-cluster-name>

  #   - name: Deploy to EKS (prod)
  #     run: |
  #       kubectl apply -f service/deployment.yaml -n prod # Triển khai vào namespace prod
  #       kubectl apply -f service/service.yaml -n prod
  #       kubectl apply -f service/ingress.yaml -n prod
